language: android
jdk:
  - oraclejdk8
notifications:
  email: false
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-25

    # Support Library
    - extra-android-support

    # Design Support Library
    - extra-android-m2repository

    # Google Play Services
    - extra-google-m2repository

before_install:
  - cd ./android/app
  - openssl aes-256-cbc -K $encrypted_c6022a83bfc2_key -iv $encrypted_c6022a83bfc2_iv -in google-services.json.enc -out google-services.json -d
  - cd ..

script:
  - ./gradlew assemble
